# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: certificate-dns-bridge
version: 0.1.0
