# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "certificate-dns-bridge.fullname" . }}
  labels:
    app: {{ include "certificate-dns-bridge.name" . }}
    chart: {{ include "certificate-dns-bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "certificate-dns-bridge.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: {{ include "certificate-dns-bridge.name" . }}
    chart: {{ include "certificate-dns-bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "certificate-dns-bridge.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certificate-dns-bridge.fullname" . }}:auth-delegator
  labels:
    app: {{ include "certificate-dns-bridge.name" . }}
    chart: {{ include "certificate-dns-bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "certificate-dns-bridge.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "certificate-dns-bridge.fullname" . }}:domain-solver
  labels:
    app: {{ include "certificate-dns-bridge.name" . }}
    chart: {{ include "certificate-dns-bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certificate-dns-bridge.fullname" . }}:domain-solver
  labels:
    app: {{ include "certificate-dns-bridge.name" . }}
    chart: {{ include "certificate-dns-bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certificate-dns-bridge.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "certificate-dns-bridge.fullname" . }}:dns-admin
  labels:
    app: {{ include "certificate-dns-bridge.name" . }}
    chart: {{ include "certificate-dns-bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - dns.gardener.cloud
    resources:
      - dnsentries
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certificate-dns-bridge.fullname" . }}:dns-admin
  labels:
    app: {{ include "certificate-dns-bridge.name" . }}
    chart: {{ include "certificate-dns-bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certificate-dns-bridge.fullname" . }}:dns-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "certificate-dns-bridge.fullname" . }}
    namespace: {{ .Release.Namespace }}